// Teste da API REST - Restaurantes

@baseURL = http://localhost:4000
@id = 6153a0371ce41af67e0bda0c

###
// GET - Listar todos os restaurantes
GET {{baseURL}}/restaurantes
Content-Type: application/json

###
// GET - Listar o restaurante pelo id
GET {{baseURL}}/restaurantes/{{id}}
Content-Type: application/json

####
// DELETE - Apaga um restaurante pelo id
DELETE {{baseURL}}/restaurantes/{{id}}
Content-Type: application/json

###
// POST - Incluir um novo restaurante
POST {{baseURL}}/restaurantes
Content-Type: application/json

{
   "nome": "Bar da Maria II",
   "valorMedio": 45.90,
   "descricao": "Ambiente familiar",
   "fundacao": "2019-08-03T18:45:23.511Z",
   "categoria": "614a73f1d38206c4f104473b",
   "endereco": {
      "logradouro": "Rua X",
      "bairro": "Centro",
      "cep": "13.320-180",
      "municipio": "Itu",
      "estado": "SP"
   } 
}



###
// PUT - Altera um restaurante
PUT {{baseURL}}/restaurantes
Content-Type: application/json

{ "_id": "614a73f1d38206c4f104473b",
   "nome": "Hamburguerias Veganas",
   "status": "ativo" 
}