// Teste da API REST - verduras

@baseURL = http://localhost:4000
@id = 614a73f8d38206c4f104473d

###
// GET - Listar todas as verduras
GET {{baseURL}}/verdura
Content-Type: application/json

###
// GET - Listar a verduras pelo id
GET {{baseURL}}/Verdura/{{id}}
Content-Type: application/json

####
// DELETE - Apaga uma verduras pelo id
DELETE {{baseURL}}/Verdura/{{id}}
Content-Type: application/json

###
// POST - Incluir uma nova verduras
POST {{baseURL}}/verdura
Content-Type: application/json

{
   "nome": "Quiabo",
   "tipo": "Amarelinho",
   "local": "Mercado Sâo Vicente",
   "quantidade": "61",
   "status": "ativo" 
}

###
// PUT - Altera uma verduras
PUT {{baseURL}}/Verdura
Content-Type: application/json

{ "_id": "615ba44b153578951aebbf6a",
   "nome": "Abôbora",
   "tipo": "Moranga",
   "local": "Mercadinho da Esquina",
   "quantidade": "34",
   "status": "ativo" 
}